"""Interactive Streamlit application for Machine Learning Assignment 2.

The application loads five pre-trained classifiers, presents the saved model
comparison, accepts a CSV test file, validates its schema, and displays
predictions plus assignment-required evaluation metrics whenever labels are
included.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)

PROJECT_ROOT = Path(__file__).resolve().parent
MODEL_DIR = PROJECT_ROOT / "model"
RESULTS_DIR = PROJECT_ROOT / "results"
DEFAULT_TEST_DATA = PROJECT_ROOT / "test_data.csv"
TARGET_COLUMN = "diagnosis"
CLASS_LABELS = {0: "Benign", 1: "Malignant"}
METRIC_COLUMNS = ["Accuracy", "AUC", "Precision", "Recall", "F1", "MCC"]

st.set_page_config(
    page_title="Diagnostic ML Model Studio",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded",
)


CUSTOM_CSS = """
<style>
    :root {
        --navy: #132238;
        --blue: #2f6fed;
        --soft-blue: #eef4ff;
        --teal: #168a88;
        --ink: #1d2733;
        --muted: #667085;
        --line: #dfe5ec;
        --surface: #ffffff;
    }

    .stApp {
        background:
            radial-gradient(circle at 92% 2%, rgba(47,111,237,0.09), transparent 27rem),
            linear-gradient(180deg, #f7f9fc 0%, #ffffff 28rem);
        color: var(--ink);
    }

    .block-container {
        max-width: 1320px;
        padding-top: 1.4rem;
        padding-bottom: 3rem;
    }

    .hero {
        background: linear-gradient(125deg, #132238 0%, #244a76 62%, #168a88 125%);
        border-radius: 22px;
        padding: 2rem 2.2rem;
        color: white;
        box-shadow: 0 18px 42px rgba(19,34,56,0.18);
        margin-bottom: 1.4rem;
    }

    .hero-kicker {
        font-size: 0.78rem;
        letter-spacing: 0.13em;
        text-transform: uppercase;
        opacity: 0.82;
        font-weight: 700;
    }

    .hero h1 {
        margin: 0.3rem 0 0.45rem 0;
        font-size: 2.35rem;
        line-height: 1.12;
        color: white;
    }

    .hero p {
        margin: 0;
        max-width: 900px;
        font-size: 1.02rem;
        opacity: 0.93;
        line-height: 1.55;
    }

    .info-card {
        background: var(--surface);
        border: 1px solid var(--line);
        border-radius: 16px;
        padding: 1.05rem 1.15rem;
        box-shadow: 0 8px 24px rgba(27,39,51,0.06);
        height: 100%;
    }

    .info-card strong {
        color: var(--navy);
    }

    .pill {
        display: inline-block;
        background: var(--soft-blue);
        color: #214eab;
        border: 1px solid #cadbff;
        border-radius: 999px;
        padding: 0.28rem 0.65rem;
        margin: 0.15rem 0.24rem 0.15rem 0;
        font-size: 0.82rem;
        font-weight: 650;
    }

    .winner-card {
        background: linear-gradient(135deg, #ecfff9, #eff6ff);
        border: 1px solid #a9ded5;
        border-left: 5px solid var(--teal);
        border-radius: 15px;
        padding: 1rem 1.15rem;
        margin: 0.6rem 0 1.2rem 0;
    }

    .upload-note {
        background: #fffaf0;
        border: 1px solid #f3d9a7;
        border-radius: 12px;
        padding: 0.8rem 1rem;
        color: #684f1b;
        margin-bottom: 0.9rem;
    }

    .medical-note {
        background: #fff4f4;
        border: 1px solid #f1c3c3;
        border-radius: 12px;
        padding: 0.75rem 0.95rem;
        color: #7b2929;
        font-size: 0.9rem;
    }

    [data-testid="stMetric"] {
        background: white;
        border: 1px solid var(--line);
        padding: 0.85rem;
        border-radius: 14px;
        box-shadow: 0 5px 16px rgba(27,39,51,0.05);
    }

    [data-testid="stSidebar"] {
        background: #f1f5fb;
        border-right: 1px solid #dce4ee;
    }

    div[data-baseweb="select"] > div,
    [data-testid="stFileUploaderDropzone"] {
        border-radius: 12px;
    }

    .small-muted {
        color: var(--muted);
        font-size: 0.86rem;
    }
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)


@st.cache_data
def load_json(path: Path) -> dict[str, Any] | list[Any]:
    """Load a JSON artifact once per Streamlit session."""

    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


@st.cache_data
def load_comparison_table() -> pd.DataFrame:
    """Load the precomputed metrics generated by the training script."""

    return pd.read_csv(RESULTS_DIR / "model_comparison.csv")


@st.cache_resource
def load_models() -> tuple[dict[str, Any], dict[str, Any]]:
    """Load all model pipelines and their project metadata."""

    metadata = load_json(MODEL_DIR / "training_metadata.json")
    models: dict[str, Any] = {}
    for model_name, artifact_name in metadata["model_artifacts"].items():
        models[model_name] = joblib.load(MODEL_DIR / artifact_name)
    return models, metadata


def compute_metrics(
    y_true: pd.Series, predictions: np.ndarray, probabilities: np.ndarray
) -> dict[str, float]:
    """Calculate the six metrics required by the assignment."""

    auc_value = (
        float(roc_auc_score(y_true, probabilities))
        if pd.Series(y_true).nunique() == 2
        else float("nan")
    )
    return {
        "Accuracy": float(accuracy_score(y_true, predictions)),
        "AUC": auc_value,
        "Precision": float(precision_score(y_true, predictions, zero_division=0)),
        "Recall": float(recall_score(y_true, predictions, zero_division=0)),
        "F1": float(f1_score(y_true, predictions, zero_division=0)),
        "MCC": float(matthews_corrcoef(y_true, predictions)),
    }


def validate_uploaded_frame(
    frame: pd.DataFrame, expected_features: list[str]
) -> tuple[pd.DataFrame, pd.Series | None, list[str]]:
    """Validate CSV columns and return model-ready features plus optional labels."""

    if frame.empty:
        raise ValueError("The uploaded CSV contains no data rows.")

    missing_features = [name for name in expected_features if name not in frame.columns]
    if missing_features:
        raise ValueError(
            "Missing required feature columns: " + ", ".join(missing_features)
        )

    allowed_columns = set(expected_features + [TARGET_COLUMN])
    extra_columns = [name for name in frame.columns if name not in allowed_columns]

    feature_frame = frame[expected_features].copy()
    for column in expected_features:
        feature_frame[column] = pd.to_numeric(feature_frame[column], errors="raise")

    if feature_frame.isna().any().any():
        missing_locations = np.argwhere(feature_frame.isna().to_numpy())
        first_row, first_column = missing_locations[0]
        raise ValueError(
            "Missing numeric value found at data row "
            f"{int(first_row) + 2}, column '{expected_features[int(first_column)]}'."
        )

    labels: pd.Series | None = None
    if TARGET_COLUMN in frame.columns:
        labels = pd.to_numeric(frame[TARGET_COLUMN], errors="raise").astype(int)
        invalid_values = sorted(set(labels) - {0, 1})
        if invalid_values:
            raise ValueError(
                "The diagnosis column must contain only 0 (Benign) or 1 "
                f"(Malignant). Invalid values: {invalid_values}"
            )
        if labels.isna().any():
            raise ValueError("The diagnosis column contains missing values.")

    return feature_frame, labels, extra_columns


def prediction_table(
    original_frame: pd.DataFrame,
    predictions: np.ndarray,
    probabilities: np.ndarray,
    labels: pd.Series | None,
) -> pd.DataFrame:
    """Build a downloadable results table."""

    results = original_frame.copy()
    results["predicted_diagnosis"] = predictions.astype(int)
    results["predicted_label"] = pd.Series(predictions).map(CLASS_LABELS)
    results["benign_probability"] = 1.0 - probabilities
    results["malignant_probability"] = probabilities
    if labels is not None:
        results["correct_prediction"] = predictions == labels.to_numpy()
    return results


def render_metric_cards(metrics: dict[str, float]) -> None:
    columns = st.columns(6)
    for column, metric_name in zip(columns, METRIC_COLUMNS):
        column.metric(metric_name, f"{metrics[metric_name]:.4f}")


def render_confusion_matrix(
    labels: pd.Series, predictions: np.ndarray, model_name: str
) -> None:
    matrix = confusion_matrix(labels, predictions, labels=[0, 1])
    display = ConfusionMatrixDisplay(
        confusion_matrix=matrix,
        display_labels=[CLASS_LABELS[0], CLASS_LABELS[1]],
    )
    figure, axis = plt.subplots(figsize=(5.8, 4.6))
    display.plot(ax=axis, cmap="Blues", colorbar=False, values_format="d")
    axis.set_title(f"{model_name} - Confusion Matrix", pad=12, fontweight="bold")
    figure.tight_layout()
    st.pyplot(figure, use_container_width=True)
    plt.close(figure)


def render_roc_curve(
    labels: pd.Series, probabilities: np.ndarray, model_name: str
) -> None:
    if labels.nunique() < 2:
        st.info("ROC curve and AUC require both Benign and Malignant rows.")
        return
    false_positive_rate, true_positive_rate, _ = roc_curve(labels, probabilities)
    auc_value = roc_auc_score(labels, probabilities)
    figure, axis = plt.subplots(figsize=(5.8, 4.6))
    axis.plot(
        false_positive_rate,
        true_positive_rate,
        linewidth=2.4,
        label=f"{model_name} (AUC={auc_value:.4f})",
    )
    axis.plot([0, 1], [0, 1], linestyle="--", linewidth=1.2, label="Random baseline")
    axis.set_xlabel("False Positive Rate")
    axis.set_ylabel("True Positive Rate")
    axis.set_title("Receiver Operating Characteristic", pad=12, fontweight="bold")
    axis.grid(alpha=0.25)
    axis.legend(loc="lower right")
    figure.tight_layout()
    st.pyplot(figure, use_container_width=True)
    plt.close(figure)


def render_classification_report(
    labels: pd.Series, predictions: np.ndarray
) -> None:
    report = classification_report(
        labels,
        predictions,
        labels=[0, 1],
        target_names=["Benign", "Malignant"],
        output_dict=True,
        zero_division=0,
    )
    report_frame = pd.DataFrame(report).transpose()
    st.dataframe(
        report_frame.style.format(
            {
                "precision": "{:.4f}",
                "recall": "{:.4f}",
                "f1-score": "{:.4f}",
                "support": "{:.0f}",
            }
        ),
        use_container_width=True,
    )


def evaluate_all_models(
    models: dict[str, Any], features: pd.DataFrame, labels: pd.Series
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for model_name, model in models.items():
        predictions = model.predict(features)
        probabilities = model.predict_proba(features)[:, 1]
        rows.append({"ML Model Name": model_name, **compute_metrics(labels, predictions, probabilities)})
    return pd.DataFrame(rows)[["ML Model Name", *METRIC_COLUMNS]]


models, metadata = load_models()
feature_names = load_json(MODEL_DIR / "feature_names.json")
comparison = load_comparison_table()

st.markdown(
    """
    <section class="hero">
        <div class="hero-kicker">BITS WILP · Machine Learning Assignment 2</div>
        <h1>Diagnostic ML Model Studio</h1>
        <p>
            Compare five classification algorithms and test them on Breast Cancer
            Wisconsin diagnostic records. Upload a labelled CSV to reproduce all
            required metrics, or upload feature-only data to generate predictions.
        </p>
    </section>
    """,
    unsafe_allow_html=True,
)

with st.sidebar:
    st.markdown("### Assignment Profile")
    st.write("**Student:** Divyendu Shekhar")
    st.write("**BITS ID:** 2025AC05281")
    st.write("**Programme:** M.Tech (AIML)")
    st.write("**Section:** 2")
    st.divider()
    st.markdown("### Dataset Snapshot")
    st.write(f"**Source instances:** {metadata['source_instances']}")
    st.write(f"**Training instances:** {metadata['training_instances']}")
    st.write(f"**Test instances:** {metadata['test_instances']}")
    st.write(f"**Features:** {metadata['feature_count']}")
    st.write("**Positive class:** Malignant (1)")
    st.divider()
    st.markdown(
        "<div class='medical-note'><strong>Educational demonstration only.</strong><br>"
        "Predictions from this app must not be used for medical diagnosis or treatment.</div>",
        unsafe_allow_html=True,
    )

summary_columns = st.columns(4)
summary_columns[0].markdown(
    "<div class='info-card'><strong>Dataset</strong><br>Breast Cancer Wisconsin (Diagnostic)</div>",
    unsafe_allow_html=True,
)
summary_columns[1].markdown(
    "<div class='info-card'><strong>Task</strong><br>Binary classification</div>",
    unsafe_allow_html=True,
)
summary_columns[2].markdown(
    "<div class='info-card'><strong>Models</strong><br>5 prescribed classifiers</div>",
    unsafe_allow_html=True,
)
summary_columns[3].markdown(
    "<div class='info-card'><strong>Evaluation</strong><br>6 required metrics</div>",
    unsafe_allow_html=True,
)

st.markdown(
    f"""
    <div class="winner-card">
        <strong>Overall winner on the supplied test data: {metadata['winner']}</strong><br>
        Selected using {metadata['winner_selection_rule'].lower()}.
    </div>
    """,
    unsafe_allow_html=True,
)

overview_tab, upload_tab, guide_tab = st.tabs(
    ["Model Comparison", "Upload Test Data", "CSV Guide"]
)

with overview_tab:
    st.subheader("Saved experiment results")
    st.caption(
        "These values were produced from the 114-row supplied test_data.csv. "
        "All rows were excluded from model training."
    )

    display_comparison = comparison.copy()
    for metric in METRIC_COLUMNS:
        display_comparison[metric] = display_comparison[metric].round(4)
    st.dataframe(display_comparison, use_container_width=True, hide_index=True)

    chart_frame = comparison.set_index("ML Model Name")[METRIC_COLUMNS]
    st.bar_chart(chart_frame, height=430)

    st.markdown("#### Model-specific observations")
    observation_cards = {
        "Logistic Regression": (
            "Highest AUC (0.9970) and perfect malignant-class precision on the supplied test data. "
            "Its five false negatives reduced recall compared with Random Forest."
        ),
        "Decision Tree": (
            "Easy to interpret, but it produced the lowest AUC and MCC. Its single-tree structure "
            "was more sensitive to the training partition."
        ),
        "kNN": (
            "Standardisation allowed distance-based learning to work well. It achieved high AUC "
            "and precision, although six malignant records were missed."
        ),
        "Naive Bayes": (
            "Produced a strong AUC despite its conditional-independence assumption, but correlated "
            "cell-nucleus measurements reduced its classification accuracy and recall."
        ),
        "Random Forest (Ensemble)": (
            "Best overall balance: highest accuracy, recall, F1 and MCC, with only one false positive "
            "and three false negatives."
        ),
    }
    for model_name, observation in observation_cards.items():
        st.markdown(
            f"<div class='info-card'><strong>{model_name}</strong><br>{observation}</div><br>",
            unsafe_allow_html=True,
        )

with upload_tab:
    st.subheader("Evaluate a model on CSV data")
    st.markdown(
        "<div class='upload-note'>Upload only test data. Include the <code>diagnosis</code> "
        "column to calculate Accuracy, AUC, Precision, Recall, F1 and MCC. Omit it for "
        "prediction-only use.</div>",
        unsafe_allow_html=True,
    )

    control_left, control_right = st.columns([1.35, 1])
    with control_left:
        selected_model_name = st.selectbox(
            "Select classification model",
            options=list(models.keys()),
            index=list(models.keys()).index(metadata["winner"]),
        )
    with control_right:
        data_source = st.radio(
            "Data source",
            options=["Upload CSV", "Use supplied test_data.csv"],
            horizontal=True,
        )

    uploaded_file = None
    if data_source == "Upload CSV":
        uploaded_file = st.file_uploader(
            "Choose a CSV file",
            type=["csv"],
            help="The required feature names and order are shown in the CSV Guide tab.",
        )

    input_frame: pd.DataFrame | None = None
    if data_source == "Use supplied test_data.csv":
        input_frame = pd.read_csv(DEFAULT_TEST_DATA)
    elif uploaded_file is not None:
        try:
            input_frame = pd.read_csv(uploaded_file)
        except Exception as error:
            st.error(f"The CSV could not be read: {error}")

    if input_frame is None:
        st.info("Choose the supplied test file or upload a CSV to begin.")
    else:
        st.markdown("#### Input preview")
        st.caption(f"Rows: {len(input_frame):,} · Columns: {len(input_frame.columns):,}")
        st.dataframe(input_frame.head(12), use_container_width=True, hide_index=True)

        try:
            features, labels, extra_columns = validate_uploaded_frame(
                input_frame, feature_names
            )
            if extra_columns:
                st.warning(
                    "The following extra columns were ignored: " + ", ".join(extra_columns)
                )

            selected_model = models[selected_model_name]
            predictions = selected_model.predict(features).astype(int)
            probabilities = selected_model.predict_proba(features)[:, 1]
            results = prediction_table(
                input_frame, predictions, probabilities, labels
            )

            st.success(
                f"{selected_model_name} processed {len(features):,} rows successfully."
            )

            if labels is not None:
                st.markdown("#### Assignment evaluation metrics")
                current_metrics = compute_metrics(labels, predictions, probabilities)
                render_metric_cards(current_metrics)

                st.markdown("#### Diagnostic views")
                confusion_column, roc_column = st.columns(2)
                with confusion_column:
                    render_confusion_matrix(labels, predictions, selected_model_name)
                with roc_column:
                    render_roc_curve(labels, probabilities, selected_model_name)

                st.markdown("#### Classification report")
                render_classification_report(labels, predictions)

                with st.expander("Compare all five models on this uploaded labelled dataset"):
                    all_model_results = evaluate_all_models(models, features, labels)
                    display_all = all_model_results.copy()
                    for metric in METRIC_COLUMNS:
                        display_all[metric] = display_all[metric].round(4)
                    st.dataframe(display_all, use_container_width=True, hide_index=True)
            else:
                st.info(
                    "No diagnosis column was supplied, so evaluation metrics cannot be calculated. "
                    "Predictions and probabilities are shown below."
                )

            st.markdown("#### Prediction results")
            compact_columns = [
                column
                for column in [
                    TARGET_COLUMN,
                    "predicted_diagnosis",
                    "predicted_label",
                    "benign_probability",
                    "malignant_probability",
                    "correct_prediction",
                ]
                if column in results.columns
            ]
            st.dataframe(
                results[compact_columns].style.format(
                    {
                        "benign_probability": "{:.4f}",
                        "malignant_probability": "{:.4f}",
                    }
                ),
                use_container_width=True,
                hide_index=True,
            )
            st.download_button(
                "Download prediction results",
                data=results.to_csv(index=False).encode("utf-8"),
                file_name=f"{selected_model_name.lower().replace(' ', '_')}_predictions.csv",
                mime="text/csv",
            )

        except Exception as error:
            st.error(f"CSV validation or prediction failed: {error}")

with guide_tab:
    st.subheader("CSV schema and class convention")
    st.write(
        "The app expects the 30 numeric feature columns below. A labelled test file may also "
        "include `diagnosis`, where 0 means Benign and 1 means Malignant."
    )

    feature_table = pd.DataFrame(
        {
            "Position": range(1, len(feature_names) + 1),
            "Required feature column": feature_names,
            "Data type": ["Numeric"] * len(feature_names),
        }
    )
    st.dataframe(feature_table, use_container_width=True, hide_index=True)

    sample_bytes = (PROJECT_ROOT / "sample_upload_without_target.csv").read_bytes()
    st.download_button(
        "Download feature-only sample CSV",
        data=sample_bytes,
        file_name="sample_upload_without_target.csv",
        mime="text/csv",
    )

    st.markdown("#### Implemented models")
    for model_name in models:
        st.markdown(f"<span class='pill'>{model_name}</span>", unsafe_allow_html=True)

    st.markdown("#### Required evaluation metrics")
    for metric_name in METRIC_COLUMNS:
        st.markdown(f"<span class='pill'>{metric_name}</span>", unsafe_allow_html=True)

st.markdown(
    "<p class='small-muted'>Dataset: UCI Breast Cancer Wisconsin (Diagnostic), loaded through "
    "scikit-learn. Target convention used by this project: 1 = Malignant, 0 = Benign.</p>",
    unsafe_allow_html=True,
)
